source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'EquilateralLayoutDemo' do
    pod 'EquilateralLayout', :path => '..'
    pod 'PINRemoteImage', '= 3.0.0-beta.8'
end
